### ISSUE TITLE
FromStream Examples?

### ISSUE THREAD

**Issue by SykoScicle** [olmelabs/EdiEngine#10]
Attempting to write a console app that reads a basic X12 850 file to a filestream and parse it with EdiEngine. 

In the example in Wiki, it shows using FromString as below. 
 
```
EdiDataReader r = new EdiDataReader();
EdiBatch b = r.FromString(edi);
```
I saw that FromStream was an option, which accepts an open stream. I changed it to the below.

```
EdiDataReader r = new EdiDataReader();
EdiBatch b = r.FromStream(fs);
```

fs being the open file stream. However, when I do this, I get the error "Could not load file or assembly 'EDIEngine.Standards.X12_002040' or one of its dependencies. 

I noticed that in the package location no EDIEngine.Standards.X12_002040 file exists. Any guidance you can provide on this would be appreciated. I must be doing something wrong.  If you could provide proper usage for working with a stream, that would be helpful.

Full Code Being Used:
```
           string testDocPath = @"c:\users\sbarb\Documents\X12_810_00204.txt";

            FileStream fs = new FileStream(testDocPath, FileMode.Open, FileAccess.Read);
        

            EdiDataReader r = new EdiDataReader();
            EdiBatch b = r.FromStream(fs);

            //Serialize the whole batch to JSON
            JsonDataWriter w1 = new JsonDataWriter();
            string json = w1.WriteToString(b);

            //OR Serialize selected EDI message to Json
            string jsonTrans = JsonConvert.SerializeObject(b.Interchanges[0].Groups[0].Transactions[0]);

            //Serialize the whole batch to XML
            XmlDataWriter w2 = new XmlDataWriter();
            string xml = w2.WriteToString(b);

            fs.Close();
            Console.WriteLine("End of Program, hit any key to end");
            Console.ReadLine();
```

**Comment by olmelabs** [comment]
Hi,
Currently  project has only 4010 version of X12 maps.
Seems you are uploading X12 2040 file. 
It is not connected to FromStream, just absense ofmaps.
Can you play with 4010 files to find if the project suites your needs? 
If yes - i can craft 2040 maps and update NuGet (but it will take some time)
Alternatively you can try craftng it yourself by copying everything from 4010 maps, just changing version everywhere.

Regards

**Comment by SykoScicle** [comment]
AHH, As soon as my head hit the pillow I had a feeling it may be that, thank you! I'll give that a try and update. Thanks.
