### ISSUE TITLE
DataElementValidator has incorrect time format string for 24h time format.

### ISSUE THREAD

**Issue by sayfulloev** [olmelabs/EdiEngine#12]
EDI uses 24h time format, however DataElementValidator uses 12 h format string in TryParseExact() method.

**Comment by olmelabs** [comment]
This is already fixed id "develop" branch. Commit fb0eaa7

**Comment by olmelabs** [comment]
I believe end of august - early september

**Comment by olmelabs** [comment]
1.5.2 package now has the fix
