### ISSUE TITLE
Unable to find EdiDataElement when adding Content to Segment

### ISSUE THREAD

**Issue by Trashy070** [olmelabs/EdiEngine#13]
Hi there, I have been trying to work through your samples. 

I am unable to see how I can add a DataElement to a Content. 
Your example is 
var seg = new EdiSegment(sDef);
            seg.Content.AddRange(new[] {
                new EdiDataElement(sDef.Content[0], "N"),
                new EdiDataElement(sDef.Content[1], "538686"),
                new EdiDataElement(sDef.Content[2], null),
                new EdiDataElement(sDef.Content[3], "001001"),
                new EdiDataElement(sDef.Content[4], "538686")
            });
However It will not compile as I am unable to find the find out where EdiDataElement is ??
Could you please help ??

**Comment by olmelabs** [comment]
Hi, 
Have you installed nuget package?

**Comment by Trashy070** [comment]
I definitely did. As per the installation instruction in the wiki.Sent from IBM Verseolmelabs --- Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13) --- From:"olmelabs" <notifications@github.com>To:"olmelabs/EdiEngine" <EdiEngine@noreply.github.com>Cc:"Trashy070" <andy.duggan@ctcorp.com.au>, "Author" <author@noreply.github.com>Date:Fri, 5 Oct. 2018 8:13 pmSubject:Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)Hi,
Have you installed nuget package?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olmelabs/EdiEngine","title":"olmelabs/EdiEngine","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/olmelabs/EdiEngine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@olmelabs in #13: Hi, \r\nHave you installed nuget package?"}],"action":{"name":"View Issue","url":"https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427314313"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427314313",
"url": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427314313",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)",
"sections": [
{
"text": "",
"activityTitle": "**olmelabs**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@olmelabs",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427314313"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388469509\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by olmelabs** [comment]
My bad - i edited my answer - please see updated wiki sample
https://github.com/olmelabs/EdiEngine/wiki/Write-EDI-Envelope

**Comment by Trashy070** [comment]
Ahh. I tried that but forgot about the cast. Great stuff. Thank you.Sent from IBM Verseolmelabs --- Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13) --- From:"olmelabs" <notifications@github.com>To:"olmelabs/EdiEngine" <EdiEngine@noreply.github.com>Cc:"Trashy070" <andy.duggan@ctcorp.com.au>, "Author" <author@noreply.github.com>Date:Fri, 5 Oct. 2018 11:51 pmSubject:Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)My bad - i edited my answer - please see updated wiki sample
https://github.com/olmelabs/EdiEngine/wiki/Write-EDI-Envelope

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olmelabs/EdiEngine","title":"olmelabs/EdiEngine","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/olmelabs/EdiEngine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@olmelabs in #13: My bad - i edited my answer - please see updated wiki sample\r\nhttps://github.com/olmelabs/EdiEngine/wiki/Write-EDI-Envelope"}],"action":{"name":"View Issue","url":"https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427372913"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427372913",
"url": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427372913",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)",
"sections": [
{
"text": "",
"activityTitle": "**olmelabs**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@olmelabs",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427372913"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388469509\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Trashy070** [comment]
Thankyou for your assistance so far, could I please ask you one more
question ?

I need to create a Loop and I can’t quite figure out how to define it.

I assume that I need to instantiate the ParentLoop somehow but not sure on
how it is supposed to be done.

TIA





Sent from Mail for Windows 10

**Comment by Trashy070** [comment]
Ahhh. I figured it out.

Create the ParentLoop Instance.

Then add the Segments to the ParentLoop and

All good.





Sent from Mail for Windows 10



From: Andy Duggan
Sent: Saturday, 6 October 2018 7:33 PM
To: olmelabs/EdiEngine
Subject: RE: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding
Content to Segment (#13)

**Comment by olmelabs** [comment]
Just in case of writer - if you look at test project, there is a file
\EdiEngine\EdiEngine.Tests\EdiWriterTests.cs
There are some examples of writing EDI, with loops, composites, etc..

**Comment by Trashy070** [comment]
Thank you very much. This is very goodSent from IBM Verseolmelabs --- Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13) --- From:"olmelabs" <notifications@github.com>To:"olmelabs/EdiEngine" <EdiEngine@noreply.github.com>Cc:"Trashy070" <andy.duggan@ctcorp.com.au>, "Author" <author@noreply.github.com>Date:Sat, 6 Oct. 2018 8:41 pmSubject:Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)Just in case of writer - if you look at test project, there is a file
\EdiEngine\EdiEngine.Tests\EdiWriterTests.cs
There are some examples of writing EDI, with loops, composites, etc..

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/olmelabs/EdiEngine","title":"olmelabs/EdiEngine","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/olmelabs/EdiEngine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@olmelabs in #13: Just in case of writer - if you look at test project, there is a file\r\n\\EdiEngine\\EdiEngine.Tests\\EdiWriterTests.cs\r\nThere are some examples of writing EDI, with loops, composites, etc.."}],"action":{"name":"View Issue","url":"https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427563947"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427563947",
"url": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427563947",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [olmelabs/EdiEngine] Unable to find EdiDataElement when adding Content to Segment (#13)",
"sections": [
{
"text": "",
"activityTitle": "**olmelabs**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@olmelabs",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"olmelabs/EdiEngine\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/olmelabs/EdiEngine/issues/13#issuecomment-427563947"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388469509\n}"
}
],
"themeColor": "26292E"
}
]
