### ISSUE TITLE
Failed to construct EdiBatch from string 

### ISSUE THREAD

**Issue by happytrails** [olmelabs/EdiEngine#14]
Ran the example at https://github.com/olmelabs/EdiEngine/wiki/Reading-EDI-and-Writing-JSON-or-XML, but             EdiBatch b = r.FromString(edi) failed w/ this error:
mscorlib: Exception while executing function: ConvertToJson. EdiEngine: Unable to find type EdiEngine.Standards.X12_004010.Segments.ISA in assembly EdiEngine.Standards.X12_004010.

I did follow the steps https://github.com/olmelabs/EdiEngine/wiki/Using-custom-maps to add custom segments and map. Am I missing something?

**Comment by olmelabs** [comment]
Hi Kevin!
If I copy code from example into VS2015, restore package, run sample - it works for me.
Can you share you sample project with me?  So i can have a deeper look?

**Comment by happytrails** [comment]
Thank you for your response olmelabs!  It turned out to be dependency issue (newtonsoft.dll) that I was able to resolve later.
