### ISSUE TITLE
Time validation fails for Time string with seconds and milliseconds.

### ISSUE THREAD

**Issue by sayfulloev** [olmelabs/EdiEngine#15]
If element `E_0337()` has value like `083032` then validation fails because TryParseExact has format only for time without seconds and milliseconds.

**Comment by olmelabs** [comment]
Hi Sharif,
Thanks for contributing! I have added one comment on backward compatibility with C# 6.
Once it is resolved - i will merge PR.
Thanks

**Comment by olmelabs** [comment]
Merged into develop
