### ISSUE TITLE
Sending Ack to trading partner?

### ISSUE THREAD

**Issue by tekinc** [olmelabs/EdiEngine#18]
Do you have any suggestions on clients that I can use to actually send the ack?

**Comment by olmelabs** [comment]
It mainly depends on trading partner connectivity requirements. It may be as simple as SFTP, but may also require to connect via VAN or AS2.
In case AS2 is enough you may use Opne AS2 (https://github.com/OpenAS2)
In case of VAN you can connect via EasyLink (former www.icc.net) or any other VAN provider.
