### ISSUE TITLE
Error on reading EDI

### ISSUE THREAD

**Issue by mweiss219** [olmelabs/EdiEngine#21]
When I try to use EdiDataReader .FromString(edi) as in this example https://github.com/olmelabs/EdiEngine/wiki/Generate-EDI-997---Functional-Acknowledgment
I get the following error:
**Unable to find type EdiEngine.Standards.X12_004010.Segments.ISA in assembly EdiEngine.Standards.X12_004010**

I tried with multiple different EDI files, they all get the same error

Please advise

Thanks

**Comment by olmelabs** [comment]
Send me sample console project please

Best regards,
Oleg

**Comment by mweiss219** [comment]
Thanks for your quick response.
Funny that It’s working now. Looks like the reference was not resolved correctly, or something alike visual studio problem.

Thanks anyway

**Comment by MuthupandiG** [comment]
HI, 
Could you share the fix How to resolve this? Because I am also facing the same.

Here is where I got the exception,

![EDIRead_Exception](https://user-images.githubusercontent.com/35329912/94697101-6bc35900-0355-11eb-986a-e33057b9e551.jpeg)

Thanks In Advance

**Comment by mweiss219** [comment]
I was able to fix it by explicitly referencing the assembly, 
adding this line in top
var x = New EdiEngine.Standards.X12_004010.Segments.ISA();

**Comment by olmelabs** [comment]
I am thinking this is kind of a problem described here
http://shorturl.at/hxKU6
solution @mweiss219 proposed is one way. 
Another would be to make a post-build event which copies dll into correct bin folder.

**Comment by MuthupandiG** [comment]
Thanks for the reply @olmelabs @mweiss219. 

The problem is with DLL reference issue and the below code solved the issue,
_var x = new EdiEngine.Standards.X12_004010.Segments.ISA();_
