### ISSUE TITLE
Could not load file or assembly 'EdiEngine.Standards.X12_005010X217'

### ISSUE THREAD

**Issue by LoveCoding73** [olmelabs/EdiEngine#28]
Getting the follow err msg when trying to read 278 edi file:

:Exception Error
  :Message: Could not load file or assembly 'EdiEngine.Standards.X12_005010X217' or one of its dependencies. The system cannot find the file specified.
  :Type: FileNotFoundException
  :Source:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
   at EdiEngine.ActivatorHelper.Instantiate(String asmName, String typeName)
   at EdiEngine.EdiDataReader.FromString(String fileContent)

Can you help me resolve? Thanks

**Comment by olmelabs** [comment]
Hi,

5010 standard is not included into package. Only 4010.

Thanks

**Comment by LoveCoding73** [comment]
Could you possible add it? Just curious

Michael H. Robinson 

    On Saturday, January 22, 2022, 04:36:16 PM EST, olmelabs ***@***.***> wrote:  
 
 

Hi,

5010 standard is not included into package. Only 4010.

Thanks


> On 22 Jan 2022, at 18:42, LoveCoding73 ***@***.***> wrote:
> 
> ﻿
> Getting the follow err msg:
> 
> :Exception Error
> :Message: Could not load file or assembly 'EdiEngine.Standards.X12_005010X217' or one of its dependencies. The system cannot find the file specified.
> :Type: FileNotFoundException
> :Source: at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
> at System.TypeNameParser.ResolveAssembly(String asmName, Func2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark) at System.TypeNameParser.ConstructType(Func2 assemblyResolver, Func4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark) at System.TypeNameParser.GetType(String typeName, Func2 assemblyResolver, Func4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark) at System.Type.GetType(String typeName, Func2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
> at EdiEngine.ActivatorHelper.Instantiate(String asmName, String typeName)
> at EdiEngine.EdiDataReader.FromString(String fileContent)
> 
> Can you help me resolve? Thanks
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by olmelabs** [comment]
Hi  Michael
I will not add the whole 5010 as I am not actively developing this at
the moment and generating maps for the whole standard version is quite time
consuming.

Which transaction sets do you need? It might be that I have them.
Another option -  you can try copying them from 4010 (they are nearly the
same - so this may work)

Thanks
Oleg

**Comment by Matthewsre** [comment]
@olmelabs,

I'm looking to generate maps for these messages based on the 5010:

837
835
834
278
277
276
271
270

I see the current mapped file here:
https://github.com/olmelabs/EdiEngine/blob/develop/EdiStandards/X12_004010/Maps/M_837.cs

But am having a tough time finding the spec data for X12 5010 to create the map file from. Any guidance for where to get these details?

**Comment by olmelabs** [comment]
Hi Matt|
Sorry for the late response,

I am no longer working actively on this project.
I see you are interested in the HIPAA set, which is not natively supported
by the library.
You can still have some EDI, but it will not comply with
HIPAA requirements. (e.g. you will have fields with qualifiers, but you
will not have proper names as per HIPAA specs)

If you are ok with just EDI, I think i can dig into what I have here (no
warranties on the quality of maps).
But it will take some time. Let me know if it is still relevant for you.

Thanks,
Oleg
